### ISSUE TITLE
v-filter breaks when a child has been removed

### ISSUE THREAD

**Issue by cwhitehouse** [cwhitehouse/vivere#1]
Error stack trace:
```
dom.js:9 Uncaught DOMException: Failed to execute 'replaceChild' on 'Node': The node to be replaced is not a child of this node.
    at Object.conditionallyRender (http://localhost:1234/main.1f19ae8e.js:1825:22)
    at http://localhost:1234/main.1f19ae8e.js:1941:26
    at Array.forEach (<anonymous>)
    at http://localhost:1234/main.1f19ae8e.js:1937:21
    at Function.watch (http://localhost:1234/main.1f19ae8e.js:385:7)
    at FilterDirective.evaluateValue (http://localhost:1234/main.1f19ae8e.js:1917:26)
    at http://localhost:1234/main.1f19ae8e.js:1649:15
    at Function.watch (http://localhost:1234/main.1f19ae8e.js:385:7)
    at FilterDirective.evaluate (http://localhost:1234/main.1f19ae8e.js:1646:24)
    at http://localhost:1234/main.1f19ae8e.js:917:14
```

**Comment by cwhitehouse** [comment]
We've removed the `v-filter` directive
